/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eyescare.gui;

import javax.swing.JOptionPane;
import eyescare.logic.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rizal Asrul Pambudi
 */
public class AdminPanel extends javax.swing.JFrame {
    private Connection c = DBConnections.getCon();
    private String sql;
    private DefaultTableModel penggunaTableModel = new DefaultTableModel();
    private DefaultTableModel penyakitTableModel = new DefaultTableModel();
    
    public AdminPanel() {
        initComponents();
        initTablePengguna();
        initTablePenyakit();
        initDataPengguna();
        initDataPenyakit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initTablePengguna() {
        this.penggunaTable.setModel(this.penggunaTableModel);
        this.penggunaTableModel.addColumn("Username");
        this.penggunaTableModel.addColumn("Password");
        this.penggunaTableModel.addColumn("Nama");
        this.penggunaTableModel.addColumn("Umur");
        this.penggunaTableModel.addColumn("Tempat Lahir");
        this.penggunaTableModel.addColumn("Status");
        this.penggunaTableModel.addColumn("Agama");
        this.penggunaTableModel.addColumn("Pekerjaan");
        this.penggunaTableModel.addColumn("Alamat");
    }
    
    private void initTablePenyakit() {
        this.penyakitTable.setModel(this.penyakitTableModel);
        penyakitTableModel.addColumn("Nama Penyakit");
        penyakitTableModel.addColumn("Deskripsi");
        penyakitTableModel.addColumn("Gejala");
        penyakitTableModel.addColumn("Solusi");
    }
    
    private void initDataPengguna() {
        ResultSet hasilQuery;
        Statement s;
        Object data[] = new Object[9];
        
        try {
            s = this.c.createStatement();
            this.sql = "SELECT pengguna.username, pengguna.password, pengguna.nama, pengguna.umur, pengguna.tempat_lahir, pengguna.status, pengguna.agama, pengguna.pekerjaan, pengguna.alamat"
                    + " FROM pengguna";
            hasilQuery = s.executeQuery(this.sql);
            while(hasilQuery.next()) {
                data[0] = hasilQuery.getString(1);
                data[1] = hasilQuery.getString(2);
                data[2] = hasilQuery.getString(3);
                data[3] = hasilQuery.getString(4);
                data[4] = hasilQuery.getString(5);
                data[5] = hasilQuery.getString(6);
                data[6] = hasilQuery.getString(7);
                data[7] = hasilQuery.getString(8);
                data[8] = hasilQuery.getString(9);
                this.penggunaTableModel.addRow(data);
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }   
    
    private void initDataPenyakit() {
        ResultSet hasilQuery;
        Statement s;
        Object data[] = new Object[4];
        
        try {
            s = this.c.createStatement();
            this.sql = "SELECT penyakit.nama_penyakit, penyakit.deskripsi_penyakit, penyakit.solusi, penyakit.gejala_penyakit"
                    + " FROM penyakit";
            hasilQuery = s.executeQuery(this.sql);
            while(hasilQuery.next()) {
                data[0] = hasilQuery.getString(1);
                data[1] = hasilQuery.getString(2);
                data[2] = hasilQuery.getString(3);
                data[3] = hasilQuery.getString(4);
                this.penyakitTableModel.addRow(data);
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        logoutButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        penggunaTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        umurLabel = new javax.swing.JLabel();
        tempatLahirLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        agamaLabel = new javax.swing.JLabel();
        pekerjaanLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        umurTextField = new javax.swing.JTextField();
        tempatLahirTextField = new javax.swing.JTextField();
        statusTextField = new javax.swing.JTextField();
        agamaTextField = new javax.swing.JTextField();
        pekerjaanTextField = new javax.swing.JTextField();
        alamatTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        penyakitTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        namaPenyakitLabel = new javax.swing.JLabel();
        namaPenyakitTextField = new javax.swing.JTextField();
        deskripsiLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        deskripsiTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        gejalaTextArea = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        solusiTextArea = new javax.swing.JTextArea();
        gejalaLabel = new javax.swing.JLabel();
        solusiLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eye Care v1.0");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/bg-icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        jLabel2.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Eye Care");

        jLabel3.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        jLabel3.setText("Sistem Pakar Penyakit Mata");

        closeButton.setBackground(new java.awt.Color(255, 153, 51));
        closeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/Close-2-icon.png"))); // NOI18N
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(154, 154, 154))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("ADMIN PANEL");

        logoutButton1.setBackground(new java.awt.Color(204, 255, 255));
        logoutButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton1.setForeground(new java.awt.Color(0, 51, 102));
        logoutButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/Log-Out-icon.png"))); // NOI18N
        logoutButton1.setText("Logout");
        logoutButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));

        penggunaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        penggunaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penggunaTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(penggunaTable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Detail Pengguna");

        namaLabel.setLabelFor(namaTextField);
        namaLabel.setText("Nama");

        umurLabel.setLabelFor(umurTextField);
        umurLabel.setText("Umur");

        tempatLahirLabel.setLabelFor(tempatLahirTextField);
        tempatLahirLabel.setText("Tempat Lahir");

        statusLabel.setLabelFor(statusTextField);
        statusLabel.setText("Status");

        agamaLabel.setLabelFor(agamaTextField);
        agamaLabel.setText("Agama");

        pekerjaanLabel.setLabelFor(pekerjaanTextField);
        pekerjaanLabel.setText("Pekerjaan");

        alamatLabel.setLabelFor(alamatTextField);
        alamatLabel.setText("Alamat");

        namaTextField.setEditable(false);
        namaTextField.setBackground(new java.awt.Color(255, 255, 255));

        umurTextField.setEditable(false);
        umurTextField.setBackground(new java.awt.Color(255, 255, 255));

        tempatLahirTextField.setEditable(false);
        tempatLahirTextField.setBackground(new java.awt.Color(255, 255, 255));

        statusTextField.setEditable(false);
        statusTextField.setBackground(new java.awt.Color(255, 255, 255));

        agamaTextField.setEditable(false);
        agamaTextField.setBackground(new java.awt.Color(255, 255, 255));

        pekerjaanTextField.setEditable(false);
        pekerjaanTextField.setBackground(new java.awt.Color(255, 255, 255));

        alamatTextField.setEditable(false);
        alamatTextField.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaLabel)
                            .addComponent(umurLabel)
                            .addComponent(tempatLahirLabel)
                            .addComponent(statusLabel)
                            .addComponent(agamaLabel)
                            .addComponent(pekerjaanLabel)
                            .addComponent(alamatLabel))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(umurTextField)
                            .addComponent(tempatLahirTextField)
                            .addComponent(statusTextField)
                            .addComponent(agamaTextField)
                            .addComponent(pekerjaanTextField)
                            .addComponent(alamatTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(namaTextField))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurLabel)
                    .addComponent(umurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempatLahirLabel)
                    .addComponent(tempatLahirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel)
                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agamaLabel)
                    .addComponent(agamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pekerjaanLabel)
                    .addComponent(pekerjaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(alamatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel5);

        jTabbedPane1.addTab("Daftar Pengguna", jScrollPane1);

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));

        penyakitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        penyakitTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penyakitTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(penyakitTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Detail Penyakit");

        namaPenyakitLabel.setText("Nama Penyakit");

        namaPenyakitTextField.setEditable(false);
        namaPenyakitTextField.setBackground(new java.awt.Color(255, 255, 255));

        deskripsiLabel.setText("Deskripsi");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        deskripsiTextArea.setEditable(false);
        deskripsiTextArea.setColumns(20);
        deskripsiTextArea.setLineWrap(true);
        deskripsiTextArea.setRows(5);
        jScrollPane5.setViewportView(deskripsiTextArea);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        gejalaTextArea.setEditable(false);
        gejalaTextArea.setColumns(20);
        gejalaTextArea.setLineWrap(true);
        gejalaTextArea.setRows(5);
        jScrollPane6.setViewportView(gejalaTextArea);

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        solusiTextArea.setEditable(false);
        solusiTextArea.setColumns(20);
        solusiTextArea.setLineWrap(true);
        solusiTextArea.setRows(5);
        jScrollPane7.setViewportView(solusiTextArea);

        gejalaLabel.setText("Gejala");

        solusiLabel.setText("Solusi");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deskripsiLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(namaPenyakitLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(gejalaLabel)
                            .addComponent(solusiLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane7)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(namaPenyakitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 164, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPenyakitLabel)
                    .addComponent(namaPenyakitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deskripsiLabel)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gejalaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solusiLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel6);

        jTabbedPane1.addTab("Daftar Penyakit", jScrollPane2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(226, 226, 226))
            .addComponent(jTabbedPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6))
                    .addComponent(logoutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin keluar?",
            "Peringatan",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton1ActionPerformed
        Login login = new Login();
        JOptionPane.showMessageDialog(null, "Terima Kasih Telah Menggunakan Aplikasi Eye Care");
        login.setLocation(this.getLocation());
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButton1ActionPerformed

    private void penggunaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penggunaTableMouseClicked
        String nama, umur, tempatLahir, status, agama, pekerjaan, alamat;
        int baris;
        
        baris = this.penggunaTable.getSelectedRow();
        nama = (String) this.penggunaTable.getValueAt(baris, 2);
        umur = (String) this.penggunaTable.getValueAt(baris, 3);
        tempatLahir = (String) this.penggunaTable.getValueAt(baris, 4);
        status = (String) this.penggunaTable.getValueAt(baris, 5);
        agama = (String) this.penggunaTable.getValueAt(baris, 6);
        pekerjaan = (String) this.penggunaTable.getValueAt(baris, 7);
        alamat = (String) this.penggunaTable.getValueAt(baris, 8);
        this.namaTextField.setText(nama);
        this.umurTextField.setText(umur);
        this.tempatLahirTextField.setText(tempatLahir);
        this.statusTextField.setText(status);
        this.agamaTextField.setText(agama);
        this.pekerjaanTextField.setText(pekerjaan);
        this.alamatTextField.setText(alamat);        
    }//GEN-LAST:event_penggunaTableMouseClicked

    private void penyakitTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penyakitTableMouseClicked
        String namaPenyakit, deskripsi, solusi, gejala;
        int baris;
        
        baris = this.penyakitTable.getSelectedRow();
        namaPenyakit = (String) this.penyakitTable.getValueAt(baris, 0);
        deskripsi = (String) this.penyakitTable.getValueAt(baris, 1);
        solusi = (String) this.penyakitTable.getValueAt(baris, 2);
        gejala = (String) this.penyakitTable.getValueAt(baris, 3);
        this.namaPenyakitTextField.setText(namaPenyakit);
        this.deskripsiTextArea.setText(deskripsi);
        this.solusiTextArea.setText(solusi);
        this.gejalaTextArea.setText(gejala);
    }//GEN-LAST:event_penyakitTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agamaLabel;
    private javax.swing.JTextField agamaTextField;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextField alamatTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel deskripsiLabel;
    private javax.swing.JTextArea deskripsiTextArea;
    private javax.swing.JLabel gejalaLabel;
    private javax.swing.JTextArea gejalaTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaPenyakitLabel;
    private javax.swing.JTextField namaPenyakitTextField;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel pekerjaanLabel;
    private javax.swing.JTextField pekerjaanTextField;
    private javax.swing.JTable penggunaTable;
    private javax.swing.JTable penyakitTable;
    private javax.swing.JLabel solusiLabel;
    private javax.swing.JTextArea solusiTextArea;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JLabel tempatLahirLabel;
    private javax.swing.JTextField tempatLahirTextField;
    private javax.swing.JLabel umurLabel;
    private javax.swing.JTextField umurTextField;
    // End of variables declaration//GEN-END:variables
}
