/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eyescare.gui;

import javax.swing.JOptionPane;
import eyescare.logic.*;
import java.sql.*;
/**
 *
 * @author Rizal Asrul Pambudi
 */
public class Daftar extends javax.swing.JFrame {
    private Connection c = DBConnections.getCon();
    private String sql;
    
    public Daftar() {
        initComponents();
        initAlert();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initAlert() {
        this.usernameAlertLabel.setVisible(false);
        this.passwordAlertLabel.setVisible(false);
        this.confirmAlertLabel.setVisible(false);
        this.namaAlertLabel.setVisible(false);
        this.umurAlertLabel.setVisible(false);
        this.tempatLahirAlertLabel.setVisible(false);
        this.statusAlertLabel.setVisible(false);
        this.agamaAlertLabel.setVisible(false);
        this.pekerjaanAlertLabel.setVisible(false);
        this.alamatAlertLabel.setVisible(false);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        daftarButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        namaLabel = new javax.swing.JLabel();
        umurLabel = new javax.swing.JLabel();
        tempatLahirLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        agamaLabel = new javax.swing.JLabel();
        pekerjaanLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        umurTextField = new javax.swing.JTextField();
        tempatLahirTextField = new javax.swing.JTextField();
        agamaTextField = new javax.swing.JTextField();
        pekerjaanTextField = new javax.swing.JTextField();
        kembaliButton = new javax.swing.JButton();
        lajangRadioButton = new javax.swing.JRadioButton();
        menikahRadioButton = new javax.swing.JRadioButton();
        usernameAlertLabel = new javax.swing.JLabel();
        passwordAlertLabel = new javax.swing.JLabel();
        confirmAlertLabel = new javax.swing.JLabel();
        namaAlertLabel = new javax.swing.JLabel();
        umurAlertLabel = new javax.swing.JLabel();
        tempatLahirAlertLabel = new javax.swing.JLabel();
        statusAlertLabel = new javax.swing.JLabel();
        agamaAlertLabel = new javax.swing.JLabel();
        pekerjaanAlertLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        alamatTextField = new javax.swing.JTextField();
        alamatAlertLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        confirmPasswordTextField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eye Care v1.0");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/bg-icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        jLabel2.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Eye Care");

        jLabel3.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        jLabel3.setText("Sistem Pakar Penyakit Mata");

        closeButton.setBackground(new java.awt.Color(255, 153, 51));
        closeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/Close-2-icon.png"))); // NOI18N
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(154, 154, 154))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("REGISTRASI");

        jScrollPane1.setBorder(null);

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));

        daftarButton.setBackground(new java.awt.Color(255, 51, 0));
        daftarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        daftarButton.setForeground(new java.awt.Color(255, 255, 153));
        daftarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/Patients-icon.png"))); // NOI18N
        daftarButton.setText("DAFTAR");
        daftarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        daftarButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        daftarButton.setIconTextGap(110);
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameLabel.setLabelFor(usernameTextField);
        usernameLabel.setText("Username");

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordLabel.setLabelFor(passwordTextField);
        passwordLabel.setText("Password");

        confirmPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        confirmPasswordLabel.setLabelFor(confirmPasswordTextField);
        confirmPasswordLabel.setText("Confirm Password");

        namaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        namaLabel.setLabelFor(namaTextField);
        namaLabel.setText("Nama");

        umurLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        umurLabel.setLabelFor(umurTextField);
        umurLabel.setText("Umur");

        tempatLahirLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tempatLahirLabel.setLabelFor(tempatLahirTextField);
        tempatLahirLabel.setText("Tempat Lahir");

        statusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        statusLabel.setText("Status");

        agamaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        agamaLabel.setLabelFor(agamaTextField);
        agamaLabel.setText("Agama");

        pekerjaanLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pekerjaanLabel.setLabelFor(pekerjaanTextField);
        pekerjaanLabel.setText("Pekerjaan");

        kembaliButton.setBackground(new java.awt.Color(204, 255, 255));
        kembaliButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kembaliButton.setForeground(new java.awt.Color(0, 51, 102));
        kembaliButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/back-icon.png"))); // NOI18N
        kembaliButton.setText("Kembali");
        kembaliButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        lajangRadioButton.setBackground(new java.awt.Color(153, 255, 153));
        buttonGroup1.add(lajangRadioButton);
        lajangRadioButton.setText("Lajang");
        lajangRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menikahRadioButton.setBackground(new java.awt.Color(153, 255, 153));
        buttonGroup1.add(menikahRadioButton);
        menikahRadioButton.setText("Menikah");
        menikahRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        usernameAlertLabel.setForeground(new java.awt.Color(255, 0, 0));
        usernameAlertLabel.setText("* Username belum diisi");

        passwordAlertLabel.setForeground(new java.awt.Color(255, 0, 0));
        passwordAlertLabel.setText("* Password belum diisi");

        confirmAlertLabel.setForeground(new java.awt.Color(255, 0, 0));
        confirmAlertLabel.setText("* Password tidak sama");

        namaAlertLabel.setForeground(new java.awt.Color(255, 0, 0));
        namaAlertLabel.setText("* Nama belum diisi");

        umurAlertLabel.setForeground(new java.awt.Color(255, 0, 0));
        umurAlertLabel.setText("* Umur belum diisi");

        tempatLahirAlertLabel.setForeground(new java.awt.Color(255, 0, 0));
        tempatLahirAlertLabel.setText("* Tempat lahir belum diisi");

        statusAlertLabel.setForeground(new java.awt.Color(255, 0, 0));
        statusAlertLabel.setText("* Status belum diisi");

        agamaAlertLabel.setForeground(new java.awt.Color(255, 0, 0));
        agamaAlertLabel.setText("* Agama belum diisi");

        pekerjaanAlertLabel.setForeground(new java.awt.Color(255, 0, 0));
        pekerjaanAlertLabel.setText("* Pekerjaan belum diisi");

        alamatLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alamatLabel.setText("Alamat");

        alamatAlertLabel.setForeground(new java.awt.Color(255, 0, 0));
        alamatAlertLabel.setText("* Alamat belum diisi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(daftarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kembaliButton, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLabel)
                                    .addComponent(passwordLabel)
                                    .addComponent(confirmPasswordLabel))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameTextField)
                                    .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(confirmPasswordTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameAlertLabel)
                                    .addComponent(passwordAlertLabel)
                                    .addComponent(confirmAlertLabel)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaLabel)
                                    .addComponent(umurLabel)
                                    .addComponent(tempatLahirLabel)
                                    .addComponent(statusLabel)
                                    .addComponent(agamaLabel)
                                    .addComponent(pekerjaanLabel)
                                    .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(lajangRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menikahRadioButton)
                                        .addGap(28, 28, 28)
                                        .addComponent(statusAlertLabel))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(alamatTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                            .addComponent(namaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(umurTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tempatLahirTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(agamaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pekerjaanTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(namaAlertLabel)
                                            .addComponent(umurAlertLabel)
                                            .addComponent(tempatLahirAlertLabel)
                                            .addComponent(agamaAlertLabel)
                                            .addComponent(pekerjaanAlertLabel)
                                            .addComponent(alamatAlertLabel))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameAlertLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordAlertLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordLabel)
                    .addComponent(confirmAlertLabel)
                    .addComponent(confirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaAlertLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurLabel)
                    .addComponent(umurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(umurAlertLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempatLahirLabel)
                    .addComponent(tempatLahirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempatLahirAlertLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(lajangRadioButton)
                    .addComponent(menikahRadioButton)
                    .addComponent(statusAlertLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agamaLabel)
                    .addComponent(agamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agamaAlertLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pekerjaanLabel)
                    .addComponent(pekerjaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pekerjaanAlertLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamatLabel)
                    .addComponent(alamatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatAlertLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daftarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(226, 226, 226))
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        String username, password, nama, tempatLahir, agama, status, pekerjaan, alamat;
        int umur;
        boolean isFailed = true;
        
        isFailed = (!this.confirmPasswordTextField.getText().equals("") && (!this.passwordTextField.getText().equals(this.confirmPasswordTextField.getText()))) ||
                (this.usernameTextField.getText().equals("")) ||
                (this.namaTextField.getText().equals("")) ||
                (this.umurTextField.getText().equals("")) ||
                (this.tempatLahirTextField.getText().equals("")) ||
                (!this.lajangRadioButton.isSelected() && !this.menikahRadioButton.isSelected()) ||
                (this.agamaTextField.getText().equals("")) ||
                (this.pekerjaanTextField.getText().equals("")) ||
                (this.alamatTextField.getText().equals("")) ||
                (this.passwordTextField.getText().equals(""));
        if(!this.confirmPasswordTextField.getText().equals("") && (!this.passwordTextField.getText().equals(this.confirmPasswordTextField.getText())))
            confirmAlertLabel.setVisible(true);
        else
            this.confirmAlertLabel.setVisible(false);
        if(this.usernameTextField.getText().equals(""))
            this.usernameAlertLabel.setVisible(true);
        else 
            this.usernameAlertLabel.setVisible(false);
        if(this.namaTextField.getText().equals("")) 
            this.namaAlertLabel.setVisible(true);
        else 
            this.namaAlertLabel.setVisible(false);
        if(this.umurTextField.getText().equals("")) 
            this.umurAlertLabel.setVisible(true);
        else 
            this.umurAlertLabel.setVisible(false);
        if(this.tempatLahirTextField.getText().equals("")) 
            this.tempatLahirAlertLabel.setVisible(true);
        else 
            this.tempatLahirAlertLabel.setVisible(false);
        if(!this.lajangRadioButton.isSelected() && !this.menikahRadioButton.isSelected()) 
            this.statusAlertLabel.setVisible(true);
        else 
            this.statusAlertLabel.setVisible(false);
        if(this.agamaTextField.getText().equals("")) 
            this.agamaAlertLabel.setVisible(true);
        else 
            this.agamaAlertLabel.setVisible(false);
        if(this.pekerjaanTextField.getText().equals("")) 
            this.pekerjaanAlertLabel.setVisible(true);
        else 
            this.pekerjaanAlertLabel.setVisible(false);
        if(this.alamatTextField.getText().equals("")) 
            this.alamatAlertLabel.setVisible(true);
        else 
            this.alamatAlertLabel.setVisible(false);
        if(this.passwordTextField.getText().equals("")) 
            this.passwordAlertLabel.setVisible(true);
        else 
            this.passwordAlertLabel.setVisible(false);
        if(!isFailed) {
            username = this.usernameTextField.getText();
            password = this.passwordTextField.getText();
            nama = this.namaTextField.getText();
            tempatLahir = this.tempatLahirTextField.getText();
            agama = this.agamaTextField.getText();
            pekerjaan = this.pekerjaanTextField.getText();
            alamat = this.alamatTextField.getText();
            umur = Integer.parseInt(this.umurTextField.getText());
            if(this.lajangRadioButton.isSelected())
                status = "Lajang";
            else
                status = "Menikah";
            try {
                Statement s = c.createStatement();
                this.sql = "INSERT INTO pengguna (password, username, nama, umur, tempat_lahir, status, agama, pekerjaan, alamat) "
                        + "VALUES ('"+ password +"', '"+ username +"', '"+ nama +"', '"+ umur +"', '"+ tempatLahir +"', '"+ status +"', '"+ agama +"', '"+ pekerjaan +"', '"+ alamat +"')";
                s.executeUpdate(sql);
            } catch(SQLException e) {
                System.out.println("Error pada method setInsert()");
            }
            JOptionPane.showMessageDialog(null, "Anda berhasil mendaftar. Silahkan login kembali");
            Login login = new Login();
            login.setLocation(this.getLocation());
            login.setVisible(true);
            dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "Ada kolom yang belum Anda isi. Silahkan cek kembali");            
    }//GEN-LAST:event_daftarButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        Login login = new Login();
        login.setLocation(this.getLocation());
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin keluar?",
            "Peringatan",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agamaAlertLabel;
    private javax.swing.JLabel agamaLabel;
    private javax.swing.JTextField agamaTextField;
    private javax.swing.JLabel alamatAlertLabel;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextField alamatTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel confirmAlertLabel;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JPasswordField confirmPasswordTextField;
    private javax.swing.JButton daftarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JRadioButton lajangRadioButton;
    private javax.swing.JRadioButton menikahRadioButton;
    private javax.swing.JLabel namaAlertLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel passwordAlertLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel pekerjaanAlertLabel;
    private javax.swing.JLabel pekerjaanLabel;
    private javax.swing.JTextField pekerjaanTextField;
    private javax.swing.JLabel statusAlertLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel tempatLahirAlertLabel;
    private javax.swing.JLabel tempatLahirLabel;
    private javax.swing.JTextField tempatLahirTextField;
    private javax.swing.JLabel umurAlertLabel;
    private javax.swing.JLabel umurLabel;
    private javax.swing.JTextField umurTextField;
    private javax.swing.JLabel usernameAlertLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
