/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eyescare.gui;

import javax.swing.JOptionPane;
import eyescare.logic.*;
import java.sql.*;
/**
 *
 * @author Rizal Asrul Pambudi
 */
public class Diagnosa extends javax.swing.JFrame {
    private int indikator;
    private String pernyataan[];
    private int penyakit[];
    private String sql, kode_pengguna;
    /**
     * Creates new form Login
     */
    public Diagnosa() {
        initComponents();
        initData();
    }
    
    public Diagnosa(String kode_pengguna) {
        this.kode_pengguna = kode_pengguna;
        initComponents();
        initData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initData() {
        this.indikator = 0;
        this.pernyataan = new String[11];
        this.penyakit = new int[5];
        this.pernyataan[0] = "Ketika Anda berkaca, apakah mata anda memerah?";
        this.pernyataan[1] = "Apakah Anda sering merasakan nyeri di daerah sekitar mata?";
        this.pernyataan[2] = "Apakah mata Anda sering mengeluarkan air tanpa sebab?";
        this.pernyataan[3] = "Apakah mata Anda terlihat lebih bengkak?";
        this.pernyataan[4] = "Apakah Anda sering merasa gatal di daerah sekitar mata?";
        this.pernyataan[5] = "Apakah mata Anda sering mengeluarkan kotoran?";
        this.pernyataan[6] = "Apakah pengelihatan Anda merasa kabur ketika melihat sesuatu?";
        this.pernyataan[7] = "Apakah mata Anda terlihat keruh?";
        this.pernyataan[8] = "Apakah Anda terkadang sering merasa demam?";
        this.pernyataan[9] = "Apakah mata Anda menjadi lebih sensitif terhadap cahaya?";
        this.pernyataan[10] = "Apakah mata Anda pernah mengeluarkan cairan (selain air)?";
        this.mundurButton.setEnabled(false);
        this.diagnosaLabel.setText(pernyataan[0]);
    }
    
    private void prosesSistem() {
        if(this.indikator == 0) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[0]++;
                this.penyakit[1]++;
                this.penyakit[2]++;
                this.penyakit[4]++;
            }
        }
        else if(this.indikator == 1) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[0]++;
                this.penyakit[2]++;
                this.penyakit[4]++;
            }
        }
        else if(this.indikator == 2) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[1]++;
                this.penyakit[2]++;
                this.penyakit[3]++;
            }
        }
        else if(this.indikator == 3) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[1]++;
                this.penyakit[3]++;
            }
        }
        else if(this.indikator == 4) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[0]++;
                this.penyakit[2]++;
            }
        }
        else if(this.indikator == 5) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[0]++;
                this.penyakit[1]++;
                this.penyakit[2]++;
            }
        }
        else if(this.indikator == 6) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[0]++;
                this.penyakit[1]++;
                this.penyakit[2]++;
                this.penyakit[4]++;
            }
        }
        else if(this.indikator == 7) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[2]++;
            }
        }
        else if(this.indikator == 8) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[3]++;
            }
        }
        else if(this.indikator == 9) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[2]++;
            }
        }
        else {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[1]++;
                this.penyakit[3]++;
            }
        }
    }
    
    private void backSistem() {
        if(this.indikator == 0) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[0]--;
                this.penyakit[1]--;
                this.penyakit[2]--;
                this.penyakit[4]--;
            }
        }
        else if(this.indikator == 1) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[0]--;
                this.penyakit[2]--;
                this.penyakit[4]--;
            }
        }
        else if(this.indikator == 2) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[1]--;
                this.penyakit[2]--;
                this.penyakit[3]--;
            }
        }
        else if(this.indikator == 3) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[1]--;
                this.penyakit[3]--;
            }
        }
        else if(this.indikator == 4) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[0]--;
                this.penyakit[2]--;
            }
        }
        else if(this.indikator == 5) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[0]--;
                this.penyakit[1]--;
                this.penyakit[2]--;
            }
        }
        else if(this.indikator == 6) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[0]--;
                this.penyakit[1]--;
                this.penyakit[2]--;
                this.penyakit[4]--;
            }
        }
        else if(this.indikator == 7) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[2]--;
            }
        }
        else if(this.indikator == 8) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[3]--;
            }
        }
        else if(this.indikator == 9) {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[2]--;
            }
        }
        else {
            if(this.yaRadioButton.isSelected()) {
                this.penyakit[1]--;
                this.penyakit[3]--;
            }
        }
    }
    
    private String generateData() {
        String penyakit = "";
        
        int a = 0, temp = this.penyakit[0];
        for(int i = 0; i < 5; i++) {
            if(temp < this.penyakit[i]) {
                a = i;
                temp = this.penyakit[i];
            }
        }
        if(a == 0)
            penyakit = "SELECT penyakit.nama_penyakit, penyakit.solusi FROM penyakit WHERE penyakit.kode_penyakit = 1";
        else if(a == 1)
            penyakit = "SELECT penyakit.nama_penyakit, penyakit.solusi FROM penyakit WHERE penyakit.kode_penyakit = 5";
        else if(a == 2) 
            penyakit = "SELECT penyakit.nama_penyakit, penyakit.solusi FROM penyakit WHERE penyakit.kode_penyakit = 8";
        else if(a == 3)
            penyakit = "SELECT penyakit.nama_penyakit, penyakit.solusi FROM penyakit WHERE penyakit.kode_penyakit = 7";
        else
            penyakit = "SELECT penyakit.nama_penyakit, penyakit.solusi FROM penyakit WHERE penyakit.kode_penyakit = 3";
        return penyakit;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        diagnosaLabel = new javax.swing.JLabel();
        yaRadioButton = new javax.swing.JRadioButton();
        tidakRadioButton = new javax.swing.JRadioButton();
        mundurButton = new javax.swing.JButton();
        lanjutButton = new javax.swing.JButton();
        generateButton = new javax.swing.JButton();
        generateLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eye Care v1.0");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/bg-icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        jLabel2.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Eye Care");

        jLabel3.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        jLabel3.setText("Sistem Pakar Penyakit Mata");

        closeButton.setBackground(new java.awt.Color(255, 153, 51));
        closeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/Close-2-icon.png"))); // NOI18N
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(154, 154, 154))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(closeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 2, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("PERTANYAAN:");

        diagnosaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        diagnosaLabel.setText("jLabel5");

        yaRadioButton.setBackground(new java.awt.Color(204, 204, 255));
        yaRadioButton.setText("Ya");
        yaRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaRadioButtonActionPerformed(evt);
            }
        });

        tidakRadioButton.setBackground(new java.awt.Color(204, 204, 255));
        tidakRadioButton.setText("Tidak");
        tidakRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tidakRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakRadioButtonActionPerformed(evt);
            }
        });

        mundurButton.setBackground(new java.awt.Color(0, 204, 51));
        mundurButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/Button-Prev-icon.png"))); // NOI18N
        mundurButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mundurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mundurButtonActionPerformed(evt);
            }
        });

        lanjutButton.setBackground(new java.awt.Color(0, 204, 51));
        lanjutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/Button-Next-icon.png"))); // NOI18N
        lanjutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lanjutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutButtonActionPerformed(evt);
            }
        });

        generateButton.setBackground(new java.awt.Color(153, 255, 204));
        generateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyescare/images/medical-bed-icon.png"))); // NOI18N
        generateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generateButton.setEnabled(false);
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        generateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generateLabel.setLabelFor(generateButton);
        generateLabel.setText("Generate");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diagnosaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(mundurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lanjutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(yaRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tidakRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diagnosaLabel)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yaRadioButton)
                            .addComponent(tidakRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mundurButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lanjutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(generateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DIAGNOSA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin keluar?",
                "Peringatan",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
 
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void mundurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mundurButtonActionPerformed
        this.backSistem();
        this.indikator--;
        System.out.println(this.indikator);
        if(this.indikator < 1)
            this.mundurButton.setEnabled(false);
        else
            this.mundurButton.setEnabled(true);
        if(this.indikator > 10) {
            this.lanjutButton.setEnabled(false);
            this.generateButton.setEnabled(true);
        }
        else {
            this.lanjutButton.setEnabled(true);
            this.generateButton.setEnabled(false);
        }
        this.diagnosaLabel.setText(pernyataan[indikator]);
        if(this.yaRadioButton.isSelected())
            this.yaRadioButton.setSelected(false);
        if(this.tidakRadioButton.isSelected())
            this.tidakRadioButton.setSelected(false);
    }//GEN-LAST:event_mundurButtonActionPerformed

    private void lanjutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanjutButtonActionPerformed
        if(!this.yaRadioButton.isSelected() && !this.tidakRadioButton.isSelected())
            JOptionPane.showMessageDialog(null, "Anda belum menjawab");
        else {
            this.prosesSistem();
            if(this.indikator < 11)
                this.indikator++;
            //System.out.println(this.indikator);
            if(this.indikator < 1) 
                this.mundurButton.setEnabled(false);
            else {
                this.mundurButton.setEnabled(true);
            }
            if(this.indikator > 10) {
                this.lanjutButton.setEnabled(false);
                this.generateButton.setEnabled(true);
            }
            else {
                this.lanjutButton.setEnabled(true);
                this.generateButton.setEnabled(false);
            }
            if(this.indikator == 11)
                this.indikator = 10;
            if(this.indikator < 11)
                this.diagnosaLabel.setText(pernyataan[indikator]);
            if(this.yaRadioButton.isSelected())
                this.yaRadioButton.setSelected(false);
            if(this.tidakRadioButton.isSelected())
                this.tidakRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_lanjutButtonActionPerformed

    private void yaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaRadioButtonActionPerformed
        this.tidakRadioButton.setSelected(false);
        this.yaRadioButton.setSelected(true);
    }//GEN-LAST:event_yaRadioButtonActionPerformed

    private void tidakRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakRadioButtonActionPerformed
        this.yaRadioButton.setSelected(false);
        this.tidakRadioButton.setSelected(true);
    }//GEN-LAST:event_tidakRadioButtonActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        String penyakit = this.generateData();
        boolean isSehat = false;
        
        if(this.penyakit[0] == 0 && this.penyakit[1] == 0 && this.penyakit[2] == 0 && this.penyakit[3] == 0 && this.penyakit[4] == 0)
            isSehat = true;
        if(isSehat) {
            HasilDiagnosa hasilDiagnosa = new HasilDiagnosa(this.kode_pengguna);
            hasilDiagnosa.setLocation(this.getLocation());
            hasilDiagnosa.setVisible(true);
            this.dispose();
        }
        else {
            HasilDiagnosa hasilDiagnosa = new HasilDiagnosa(penyakit, this.kode_pengguna);
            hasilDiagnosa.setLocation(this.getLocation());
            hasilDiagnosa.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_generateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnosa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel diagnosaLabel;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel generateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton lanjutButton;
    private javax.swing.JButton mundurButton;
    private javax.swing.JRadioButton tidakRadioButton;
    private javax.swing.JRadioButton yaRadioButton;
    // End of variables declaration//GEN-END:variables
}
